apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green-pipeline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pdebuitlear/argo-rollouts-deployments.git
    targetRevision: HEAD
    path: k8s/overlays/staging-blue-green
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo-staging
  syncPolicy:
    automated: {}
