apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-istio-vs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pdebuitlear/argo-rollouts-deployments.git
    targetRevision: HEAD
    path: k8s/overlays/prod-canary-vs
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo-prod

