apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: argo-demo
namespace: argo-demo-staging
commonAnnotations:
  note: staging
resources:
- namespace.yaml
- preview-service.yaml
- ingress.yaml
- ../../base
patchesStrategicMerge:
- replica-count.yaml
- config.yaml
images:
- name: particule/simplecolorapi
  newTag: "1.0"
