commonLabels:
  app: argo-demo
namespace: argo-demo-staging
commonAnnotations:
  note: staging
resources:
  - namespace.yaml
  - preview-service.yaml
  - ingress.yaml
bases:
  - github.com/pdebuitlear/argo-rollouts-deployments/tree/main/k8s/base
patches:
  - replica_count.yaml
  - config.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-demo
    path: image.yaml