commonLabels:
  app: argo-demo
namespace: argo-demo-staging
commonAnnotations:
  note: staging
resources:
  - namespace.yaml
  - preview-service.yaml
  - ingress.yaml
bases:
  - ../../base
patches:
  - replica-count.yaml
  - config.yaml
  - deployment.yaml