commonLabels:
  app: argo-demo
namespace: argo-demo-prod-vs
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - ingress.yaml
  - preview-service.yaml
  - virtual-service.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
  - service.yaml
  - deployment.yaml
