commonLabels:
  app: argo-demo
namespace: argo-demo-prod-vs
commonAnnotations:
  note: production
resources:
- namespace.yaml
- ingress.yaml
- preview-service.yaml
- virtual-service.yaml
- ../../base
patchesStrategicMerge:
- config.yaml
- rollout.yaml
- service.yaml
images:
- name: particule/simplecolorapi
  newTag: "2.0"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
