commonLabels:
  app: argo-demo
namespace: argo-demo-prod-vs
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - ingress.yaml
  - preview-service.yaml
  - virtual-service.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argo-demo
    path: image.yaml