commonLabels:
  app: argo-demo
namespace: argo-demo-prod-vs-dr
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - ingress.yaml
  - virtual-service.yaml
  - destination-rule.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
  - service.yaml  
images:
- name: particule/simplecolorapi
  newTag: "1.0"
