commonLabels:
  app: argo-demo
namespace: argo-demo-prod-vs-dr
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - ingress.yaml
  - virtual-service.yaml
  - destination-rule.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
  - service.yaml  
  - deployment.yaml
# patchesJson6902:
#   - target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: argo-demo
#     path: image.yaml
   