commonLabels:
  app: argo-demo
namespace: argo-demo-prod
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
images:
- name: particule/simplecolorapi
  newTag: "1.0"
