commonLabels:
  app: argo-demo
namespace: argo-demo-prod
commonAnnotations:
  note: production
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
bases:
  - ../../base
patches:
  - config.yaml
  - rollout.yaml
patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: argo-demo
    path: image.yaml