apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-demo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: argo-demo
      # version: v1      
  template:
    metadata:
#      annotations:
#        sidecar.istio.io/inject: "true"    
      labels:
        app: argo-demo
        # version: v1
    spec:
      containers:
        - name: argo-demo
          image: particule/simplecolorapi
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
          - configMapRef:
              name: argo-demo-config
          ports:
          - containerPort: 5000
      
  revisionHistoryLimit: 3
